blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    #path('', views.post_list, name='post_list'),
    #path('', views.PostListView.as_view(), name='post_list'),
    path('', views.post_list, name='post_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.post_detail, name='post_detail'),
    path('<int:post_id>/share/', views.post_share, name='post_share'),
    path('tag/<slug:tag_slug>/', views.post_list, name='post_list_by_tag'),
    path('search/', views.post_search, name='post_search'),
]

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

my_website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
import jobs.views
# from django.views.generic.base import TemplateView

urlpatterns = [
    #path('', TemplateView.as_view(template_name='home.html'), name='home'),
    path('', include('static_pages.urls')),
    path('admin/', admin.site.urls),
    path('discussion_board/', include('discussion_board.urls')),
    path('jobs/', include('jobs.urls', namespace='jobs')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls')),
    path('users/', include('django.contrib.auth.urls')),
    path('weather/', include('weather.urls')),
    path('social-auth/', include('social_django.urls', namespace='social')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('shop/', include('shop.urls', namespace='shop')),
    path('stock_market/', include('stock_market.urls', namespace='stock_market')),
    # path('jobs/', jobs.views.jobs_home, name='jobs_home'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('<slug:category_slug>/', views.product_list, name='product_list_by_category'),
    path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
]

stock_market/urls.py
from django.urls import path

from . import views

app_name = 'stock_market'

urlpatterns = [
    path('', views.index, name='stock_list'),
    path('detail/<int:pk>/', views.StockDetailView.as_view(), name='stock_detail'),
    path('delete/<int:pk>/', views.StockDeleteView.as_view(), name='stock_delete'),
    path('new/', views.StockCreateView.as_view(), name='new_stock'),
]

weather/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'weather'

urlpatterns = [
    path('', views.index, name='weather_list'),
    path('detail/<int:pk>/', views.CityDetailView.as_view(), name='city_detail'),
    path('delete/<int:pk>/', views.CityDeleteView.as_view(), name='city_delete'),
    path('new/', views.CityCreateView.as_view(), name='new_city'),
]

templates/article_list.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Articles{% endblock %}

{% block content %}
<div class="container">
  <h1>Articles</h1>
  <a class="btn btn-outline-info btn" href="{% url 'article_new' %}">New article</a>
  <br>
</div>
<br>


  {% for article in object_list %}
    <div class="card">
      <div class="card-header" id="my_card-header">
        <!-- <span> {{ article.pk }}.</span> -->
        <h5 class="my_header"> {{ article.title }}</h5> &middot;
        <span class="text-muted">{{ article.author }} | {{ article.date }}</span>
      </div>
      <div class="card-body">
        {{ article.body }}
      </div>
      <div class="">
        <div class="float-right button-wrap">
          <a class='btn btn-outline-info btn-sm' href="{% url 'article_detail' article.pk %}">Detail</a>
          <a class='btn btn-outline-info btn-sm' href="{% url 'article_edit' article.pk %}">Edit</a>
          <a class='btn btn-outline-info btn-sm' href="{% url 'article_delete' article.pk %}">Delete</a>
        </div>

      </div>
      <div class="card-footer">
        {% if article.comments.all %}
        <h5 class="text-left my_header">{{ article.comments.count }} comment{{ article.comments.count|pluralize }}</h5>


        {% else %}
        <h6>No comments yet</h6>
        {% endif %}
        <div class="row float-md-right">
            <a class="btn btn-outline-info btn-sm text-right" href="{% url 'comment_new' article.pk %}">New comment</a><hr>
        </div>
        {% for comment in article.comments.all %}
          <p>
            <span class="font-weight-bold">{{ comment.author }} &middot;</span>
            {{ comment }}
            <a class="btn btn-outline-warning btn-sm" href="{% url 'comment_delete' comment.pk %}">delete</a>
          </p>
        {% endfor %}
      </div>
    </div>
    <br>
  {% endfor %}
{% endblock %}

templates/base.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
    <!-- <link rel="stylesheet" href="{% static '/discussion_board/css/shop.css' %}"> -->

    <!-- Bootstrap CSS -->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static '/discussion_board/css/blog.css' %}">
    <link rel="stylesheet" href="{% static '/discussion_board/css/shop.css' %}">
    <link rel="icon" href="{% static '/img/favicon.ico' %}"/>


    <!-- <link rel="stylesheet" href="{% static '/discussion_board/css/styles.css' %}"> -->
    {% block styles %}
    {% endblock %}
    <title>{% block title %}Erin Rosenbaum{% endblock  %}</title>
  </head>

  <body>

    <header class="mb-0">
      <div class="container-fluid px-0 mb-0">
          <nav class="nav navbar navbar-expand-md navbar-dark bg-dark flex-column flex-sm-row">
            <a class="brand nav-link pull-left flex-sm-fill text-sm-center" href="{% url 'home' %}">Erin Rosenbaum</a>
            <a class="nav-link flex-sm-fill text-md-center" href="{% url 'shop:product_list' %}">Shopping Center</a>
            <a class="nav-link flex-sm-fill text-md-center" href="{% url 'discussion_list' %}">Discussion Board</a>
            <a class="nav-link flex-sm-fill text-md-center" href="{% url 'blog:post_list' %}">My Blog</a>
            <a class="nav-link flex-sm-fill text-md-center" href="{% url 'weather:weather_list' %}">Weather</a>
            <a class="nav-link flex-sm-fill text-md-center" href="{% url 'stock_market:stock_list' %}">Stock Market</a>
            <!-- <a class="nav-link flex-sm-fill text-md-center" href="#">Sports</a> -->
            <a class="nav-link flex-sm-fill text-md-center" href="https://twitter.com/ErinLRosenbaum">Twitter</a>
            <a class="nav-link flex-sm-fill text-md-center" href="{% static 'resume_for_erin_rosenbaum.pdf' %}">Resume</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse"\
            data-target="#navbarCollapse" aria-controls="navbarCollapse"\
            aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
              {% if user.is_authenticated %}
                <ul class="navbar-nav ml-auto">
                  <li class="nav-item">
                    <a class="nav-link dropdown-toggle" href="#" id="userMenu"\
                    data-toggle="dropdown" aria-haspopup="true" aria-expanded\
                    ="false">
                      {{ user.username }}
                    </a>
                    <div class="dropdown-menu dropdown-menu-right"\
                    aria-labelledby="userMenu">
                      <a class="dropdown-item" href="{% url 'password_change' %}">Change password</a>
                      <div class="dropdown-divider"></div>
                      <a class="dropdown-item" href="{% url 'logout' %}">Log Out</a>
                    </div>
                  </li>
                </ul>
              {% else %}
                <form class="form-inline ml-auto">
                  <a href="{% url 'login' %}" class="btn btn-outline-secondary">
                  Log In</a>
                  <a href="{% url 'signup' %}" class="btn btn-primary ml-2">
                  Sign up</a>
                </form>
              {% endif %}
          </nav>
        </div>
      </div>
    </header>
   {% block content %}
   {% endblock %}

    <!-- <footer class="footer navbar-fixed-bottom" id="footer">
      <div class="text-center container">
        <p id="copy" class="float-left inline-block">Erin Rosenbaum {% now "Y" %}</p>
        <p class="float-right inline-block">
          <a href="#">Back to top</a>
        </p>
      </div>
    </footer> -->

    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script
      src="https://code.jquery.com/jquery-3.3.1.js"
      integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60="
      crossorigin="anonymous"></script>
    <script type="text/javascript"
      scr="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>

  </body>
</html>

templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Erin Rosenbaum's Home Page{% endblock %}

{% block content %}

  <div class="container m-3">
    {% if user.is_authenticated %}
      <h1 class="my-4">{{ user.username }},</h1>
      <h1 class="my-4">Thanks for checking out my website! Take a look:</h1>
    {% else %}
      <h1>Thanks for checking out my website! You're not logged-in. This website utilizes a Django custom user model for authentication.</h1>
      <p>
        <a href="{% url 'login' %}">login</a> | <a href="{% url 'signup' %}">signup</a> | <a href="{% url 'password_reset' %}">password reset</a><br>
      </p>

    {% endif %}

    <div class="container">
      <div class="row">
        <div class="col-md-4">
          <div class="card my-4 shadow-sm d-flex h-95">
            <div class="card-body h-100">
              <h5 class="card-title">Shopping Center</h5>
              <p class="card-text"><a href="{% url 'shop:product_list' %}">Take me shopping</a></p>
            </div>
          </div>
        </div>
        <br>
        <div class="col-md-4">
          <div class="card my-4 shadow-sm d-flex h-95">
            <div class="card-body h-100">
              <h5 class="card-title">Discussion Board</h5>
              <p class="card-text"><a href="{% url 'discussion_list' %}">See what everyone is talking about and then start a new conversation</a></p>
            </div>
          </div>
        </div>
        <br>
        <div class="col-md-4">
          <div class="card my-4 shadow-sm d-flex h-95">
            <div class="card-body h-100">
              <h5 class="card-title">Weather Page</h5>
              <p class="card-text"><a href="{% url 'weather:weather_list' %}">What's the weather doing in your city?</a></p>
            </div>
          </div>
        </div>
        <br>
        <div class="col-md-4">
          <div class="card my-4 shadow-sm d-flex h-95">
            <div class="card-body h-100">
              <h5 class="card-title">My Personal Blog</h5>
              <p class="card-text"><a href="{% url 'blog:post_list' %}">See what I've been ranting about</a></p>
            </div>
          </div>
        </div>
        <br>
        <div class="col-md-4">
          <div class="card my-4 shadow-sm d-flex h-95">
            <div class="card-body h-100">
              <h5 class="card-title">Stock Market</h5>
              <p class="card-text"><a href="{% url 'stock_market:stock_list' %}">Keep track of your favorite stocks</a></p>
            </div>
          </div>
        </div>
        <br>
        <div class="col-md-4">
          <div class="card my-4 shadow-sm d-flex h-95">
            <div class="card-body h-100">
              <h5 class="card-title">My Resume</h5>
              <p class="card-text"><a href="{% static 'resume_for_erin_rosenbaum.pdf' %}">Your company goes here</a></p>
            </div>
          </div>
        </div>
        <br>
        <h3>Coming soon: mobile-friendly design and django-plotly-dash stock charts</h3>
      </div>
    </div>
  <!--
  <h4 class=''>Sources:</h4>
  <p>Creating a Weather App in Django Using Python Requests </p>
  <p>https://www.youtube.com/watch?v=v7xjdXWZafY</p>
  <p>Django for Beginners. William S. Vincent</p>
  <p>Django 2 by Example. Antonio Mele </p> -->

  </div>


{% endblock %}

templates/pagination.html
<div class="pagination">
  <span class="step-links">
    {% if page.has_previous %}
      <a href="?page={{ page.previous_page_number }}">Previous</a>
    {% endif %}
    <span class="current">
      Page {{ page.number }} of {{ page.paginator.num_pages }}.
    </span>
    {% if page.has_next %}
      <a href="?page={{ page.next_page_number }}">Next</a>
    {% endif %}
  </span>
</div>

templates/shop_base.html
{% extends 'base.html' %}
{% load static %}
<title>{% block title %}Shopping Center{% endblock title %}</title>
{% block styles %}
<link rel="stylesheet" href="{% static '/discussion_board/css/just_shop.css' %}">
{% endblock %}

{% block content %}
<div id="subheader" class="">
  <div class="row align-items-center h-100">
    <div class="col-lg-4 col-sm-12 h-100 justify-content-center">
       <a class="justify-content-center align-self-center" href="{% url 'home' %}">Skip shopping for now, take me back home</a>
    </div>
    <div class="col-lg-4 col-sm-12 align-middle">
        <h1 class="d-inline-block ml-5 align-middle">Shopping Center</h1>
    </div>
    <div class="col-lg-4 col-sm-12 align-middle">
      <div class="cart align-middle">
        {% with total_items=cart|length %}
        <i class="fas fa-shopping-cart align-middle"></i>
          {% if cart|length > 0 %}
            <span class="align-middle">Your cart:
            <a class="" href="{% url 'cart:cart_detail' %}">
              {{ total_items }} item{{ total_items|pluralize }},
              ${{ cart.get_total_price }}
            </a></span>
          {% else %}
          <span class="align-middle">Your cart is empty</span>
          {% endif %}
        {% endwith %}
        </div>
    </div>
  </div>
  </div>


{% block sub_content %}
{% endblock %}

{% endblock %}

templates/signup.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}Sign up{% endblock %}

{% block content %}
<div class="container mt-3">
  <h1>Sign up</h1>
  <form class="" method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <button class="btn btn-info" type="submit">Sign up</button>
  </form>
</div>

{% endblock %}