blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    #path('', views.post_list, name='post_list'),
    #path('', views.PostListView.as_view(), name='post_list'),
    path('', views.post_list, name='post_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.post_detail, name='post_detail'),
    path('<int:post_id>/share/', views.post_share, name='post_share'),
    path('tag/<slug:tag_slug>/', views.post_list, name='post_list_by_tag'),
    path('search/', views.post_search, name='post_search'),
]

my_website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
import jobs.views
# from django.views.generic.base import TemplateView

urlpatterns = [
    #path('', TemplateView.as_view(template_name='home.html'), name='home'),
    path('', include('static_pages.urls')),
    path('admin/', admin.site.urls),
    path('discussion_board/', include('discussion_board.urls')),
    path('jobs/', include('jobs.urls', namespace='jobs')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls')),
    path('users/', include('django.contrib.auth.urls')),
    path('weather/', include('weather.urls')),
    path('social-auth/', include('social_django.urls', namespace='social')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('shop/', include('shop.urls', namespace='shop')),
    path('stock_market/', include('stock_market.urls', namespace='stock_market')),
    # path('jobs/', jobs.views.jobs_home, name='jobs_home'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

stock_market/urls.py
from django.urls import path

from . import views

app_name = 'stock_market'

urlpatterns = [
    path('', views.index, name='stock_list'),
    path('detail/<int:pk>/', views.StockDetailView.as_view(), name='stock_detail'),
    path('delete/<int:pk>/', views.StockDeleteView.as_view(), name='stock_delete'),
    path('new/', views.StockCreateView.as_view(), name='new_stock'),
]

templates/stock/new_stock.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}Add Symbol{% endblock %}
{% block styles %}
  <link rel="stylesheet" href="{% static '/discussion_board/css/styles.css' %}">
{% endblock %}

{% block content %}
<div class="">
  <div class="container pt-3">
    <h1 class="">Keep track of your favorite stocks</h1>
    <form method="post">
      {% csrf_token %}
      {{ form|crispy }}
      <button class="btn btn-outline-info" type="submit">Add symbol</button>
    </form>
  </div>

</div>

{% endblock %}

templates/stock/stock_delete.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}Delete Symbol{% endblock %}
{% block styles %}
  <link rel="stylesheet" href="{% static '/discussion_board/css/styles.css' %}">
{% endblock %}

{% block content %}
<div class="">
  <div class="container pt-3">
    <h1 class="">Confirm</h1>
    <form class="" action="" method="post">
      {% csrf_token %}
      {{ form|crispy }}
      <h3>Are you sure you want to delete <span class="font-weight-bold">{{ stock.symbol }}</span> from your saved list?</h3>
      <button class="btn btn-outline-warning" type="submit">Delete</button>
      <a class="btn btn-outline-info ml-2" href="{% url 'stock_market:stock_list' %}">Cancel</a>
    </form>
  </div>

</div>

{% endblock %}

templates/stock/stock_detail.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Detail View{% endblock %}
{% block styles %}
  <link rel="stylesheet" href="{% static '/discussion_board/css/styles.css' %}">
{% endblock %}

{% block content %}

<div class="city_weather_page">
  <div class="container pt-3">
    <!-- {% for city in weather_data %} -->
    <h1>{{ object.symbol }}</h1>
      <div class="row">
        <div class="col-sm-6">

          <table id="city_detail_table" class="table table-bordered">
              <th>Description</th>
              <td>data</td>
            <tr>
              <th>Current Temp</th>
              <td>data</td>
            </tr>
            <tr>
              <th>Today's low</th>
              <td>data</td>
            </tr>
            <tr>
              <th>Today's high</th>
              <td>data</td>
            </tr>
            <tr>
              <th>Relative Humidity</th>
              <td>data</td>
            </tr>
            <tr>
              <th>Wind Speed</th>
              <td>data</td>
            </tr>
            <tr>
              <th>Barometric Pressure</th>
              <td>data</td>
            </tr>
          </table>

          <!-- {% endfor %} -->

          <p><a class="btn btn-outline-info ml-2"  href="{% url 'stock_market:stock_list' %}">Back to Stock Market Main Page</a></p>
          <p><a class="btn btn-outline-info ml-2" href="{% url 'stock_market:stock_delete' object.pk %}">Delete this symbol from saved list</a></p>
        </div>

      </div>
  </div>


</div>
{% endblock %}

templates/stock/stock_list.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}Stock Market{% endblock %}
{% block styles %}
  <link rel="stylesheet" href="{% static '/discussion_board/css/styles.css' %}">
{% endblock %}
{% block content %}
<div id="" class="">
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <h1 class="mt-3">Stock Market</h1>
          <h4 class="mb-3">Keep track of your favorite stocks. Add the ones you want, delete the ones you don't.</h4>
          <h4 class="mb-3">Limit 5 symbols per 60 seconds</h4>
          <h4 class="mb-3">Coming soon: Stock charts using django-plotly-dash</h4>
          <a class="btn btn-outline-info" href="{% url 'stock_market:new_stock' %}">Add a new symbol</a>
          <br><br>
      </div>
    </div>

      <div class="row">
        {% for stock in market_data %}
        <div class="col-md-3">
          <div class="card mb-4 border-0">
            <div id="weather_card" class="card-body">
              <h4 class="card-text">{{ stock.symbol|upper }}</h4>

              <article class="media">
                <div class="media-left">

                </div>
                <div class="media-content">
                  <div class="content">

                    <p>Open: ${{ stock.open|floatformat:"2" }}</p>
                    <p>Low: ${{ stock.low|floatformat:"2" }}</p>
                    <p>High: ${{ stock.high|floatformat:"2" }}</p>
                    <p>Price: ${{ stock.price|floatformat:"2" }}</p>
                    <p>Volume: {{ stock.volume }}</p>
                  </div>
                </div>
              </article>
              <div class="container text-center">
                <!-- <a class="btn btn-outline-info" href="{% url 'stock_market:stock_detail' stock.pk %}">Details</a> -->
                <a class="btn btn-outline-info" href="{% url 'stock_market:stock_delete' stock.pk %}">Delete</a>
              </div>


            </div>
          </div>
        </div>
        {% endfor %}
      </div>

  </div>

  </div>

{% endblock %}