blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    #path('', views.post_list, name='post_list'),
    #path('', views.PostListView.as_view(), name='post_list'),
    path('', views.post_list, name='post_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.post_detail, name='post_detail'),
    path('<int:post_id>/share/', views.post_share, name='post_share'),
    path('tag/<slug:tag_slug>/', views.post_list, name='post_list_by_tag'),
    path('search/', views.post_search, name='post_search'),
]

my_website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
import jobs.views
# from django.views.generic.base import TemplateView

urlpatterns = [
    #path('', TemplateView.as_view(template_name='home.html'), name='home'),
    path('', include('static_pages.urls')),
    path('admin/', admin.site.urls),
    path('discussion_board/', include('discussion_board.urls')),
    path('jobs/', include('jobs.urls', namespace='jobs')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls')),
    path('users/', include('django.contrib.auth.urls')),
    path('weather/', include('weather.urls')),
    path('social-auth/', include('social_django.urls', namespace='social')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('shop/', include('shop.urls', namespace='shop')),
    path('stock_market/', include('stock_market.urls', namespace='stock_market')),
    # path('jobs/', jobs.views.jobs_home, name='jobs_home'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

weather/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'weather'

urlpatterns = [
    path('', views.index, name='weather_list'),
    path('detail/<int:pk>/', views.CityDetailView.as_view(), name='city_detail'),
    path('delete/<int:pk>/', views.CityDeleteView.as_view(), name='city_delete'),
    path('new/', views.CityCreateView.as_view(), name='new_city'),
]

weather/models.py
from django.conf import settings
from django.db import models
from django.urls import reverse

class City(models.Model):
    name = models.CharField(max_length=30, unique=True)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE,blank=True, null=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('city_detail', args=[str(self.id)])

    class Meta:
        verbose_name_plural = 'cities'

weather/forms.py
from django.forms import ModelForm, TextInput
from .models import City

class CityForm(ModelForm):
    class Meta:
        model = City
        fields = ['name']
        widgets = {'name': TextInput(attrs={'class':'input', 'placeholder':'City Name'})}

weather/views.py
import requests
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
import datetime
from django.contrib.auth.mixins import LoginRequiredMixin

from .models import City
from .forms import CityForm
from . import models

def index(request):
    url = 'http://api.openweathermap.org/data/2.5/weather?q={}&units=imperial&appid=a6be6d4bc61c5dd4dcd359913154cc69'

    if request.method == 'POST':
        form = CityForm(request.POST)
        form.save()

    form = CityForm()

    cities = City.objects.all()

    weather_data = []

    for city in cities:
        resp = requests.get(url.format(city))
        # print('CONTENT \n')
        # print(resp.content)
        # print('TEXT \n')
        # print(resp.text)
        resp = requests.get(url.format(city)).json()
        if resp["cod"] != "404":

            city_weather = {
                'pk' : city.pk,
                'name' : city.name,
                #'state' : city.state,
                'pressure' : resp['main']['pressure'],
                'humidity' : resp['main']['humidity'],
                'wind_speed' : resp['wind']['speed'],
                'temp_min' : resp['main']['temp_min'],
                'temp_max' : resp['main']['temp_max'],
                'temperature' : resp['main']['temp'],
                'description' : resp['weather'][0]['description'],
                'icon' : resp['weather'][0]['icon'],
            }

            weather_data.append(city_weather)
        else:
            city.delete()

    context = {'weather_data' : weather_data, 'form' : form}
    return render(request, 'weather/weather.html', context)

class CityDetailView(DetailView):
    model = models.City
    template_name = 'weather/city_detail.html'

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        #print(context)
        url = 'http://api.openweathermap.org/data/2.5/weather?q={}&units=imperial&appid=a6be6d4bc61c5dd4dcd359913154cc69'
        my_city = City.objects.get(pk=self.kwargs['pk'])
        weather_data = []
        resp = requests.get(url.format(my_city))
        #print("RESPONSE_CONTENT")
        #print(resp.content)
        resp = requests.get(url.format(my_city)).json()

        city_weather = {
            'pk' : self.kwargs['pk'],
            'name' : City.name,
            #'state' : city.state,
            'pressure' : resp['main']['pressure'],
            'humidity' : resp['main']['humidity'],
            'wind_speed' : resp['wind']['speed'],
            'temp_min' : resp['main']['temp_min'],
            'temp_max' : resp['main']['temp_max'],
            'temperature' : resp['main']['temp'],
            'description' : resp['weather'][0]['description'],
            'icon' : resp['weather'][0]['icon'],
        }

        weather_data.append(city_weather)
        context['weather_data']=weather_data

        # print("CONTEXT")
        # print(context)
        # print("WEATHER_DATA")
        # print(weather_data)
        # print("WEATHER_DATA TEMP")
        # print(weather_data[0]['temperature'])

        return context

class CityDeleteView(DeleteView):
    model = models.City
    template_name = 'weather/city_delete.html'
    success_url = reverse_lazy('weather:weather_list')


class CityCreateView(LoginRequiredMixin, CreateView):
    model = models.City
    template_name = 'weather/new_city.html'
    fields = ['name']
    login_url = 'login'
    success_url = reverse_lazy('weather:weather_list')

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

templates/weather/city_delete.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}Delete City{% endblock %}
{% block styles %}
  <link rel="stylesheet" href="{% static '/discussion_board/css/styles.css' %}">
{% endblock %}

{% block content %}
<div class="weather_page">
  <div class="container pt-3">
    <h1 class="">Confirm</h1>
    <form class="" action="" method="post">
      {% csrf_token %}
      {{ form|crispy }}
      <h3>Are you sure you want to delete <span class="font-weight-bold">{{ city.name }}</span> from your saved list?</h3>
      <button class="btn btn-outline-warning" type="submit">Delete</button>
      <a class="btn btn-outline-info ml-2" href="{% url 'weather:weather_list' %}">Cancel</a>
    </form>
  </div>

</div>

{% endblock %}

templates/weather/city_detail.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Detail View{% endblock %}
{% block styles %}
  <link rel="stylesheet" href="{% static '/discussion_board/css/styles.css' %}">
{% endblock %}

{% block content %}


<!-- <div id="subheader" class="">
  <div class="row align-items-center h-100">
    <div class="col-lg-3 col-sm-12 h-100 justify-content-center">
      <figure class="ml-2 d-inline-block image is-50x50">
        <img src="http://openweathermap.org/img/w/{{ city.icon }}.png" alt="Image">
      </figure>
      <figure class="ml-2 d-inline-block image is-50x50">
        <img src="http://openweathermap.org/img/w/{{ city.icon }}.png" alt="Image">
      </figure>
      <figure class="ml-2 d-inline-block image is-50x50">
        <img src="http://openweathermap.org/img/w/{{ city.icon }}.png" alt="Image">
      </figure>
      <figure class="ml-2 d-inline-block image is-50x50">
        <img src="http://openweathermap.org/img/w/{{ city.icon }}.png" alt="Image">
      </figure>
      <figure class="ml-2 d-inline-block image is-50x50">
        <img src="http://openweathermap.org/img/w/{{ city.icon }}.png" alt="Image">
      </figure>
    </div>
    <div class="col-lg-6 col-sm-12 align-middle">
      <h1>Current weather in {{ object.name }}</h1>
    </div>
    <div class="col-lg-3 col-sm-12 align-middle">
      <figure class="ml-2 d-inline-block image is-50x50">
        <img src="http://openweathermap.org/img/w/{{ city.icon }}.png" alt="Image">
      </figure>
      <figure class="ml-2 d-inline-block image is-50x50">
        <img src="http://openweathermap.org/img/w/{{ city.icon }}.png" alt="Image">
      </figure>
      <figure class="ml-2 d-inline-block image is-50x50">
        <img src="http://openweathermap.org/img/w/{{ city.icon }}.png" alt="Image">
      </figure>
      <figure class="ml-2 d-inline-block image is-50x50">
        <img src="http://openweathermap.org/img/w/{{ city.icon }}.png" alt="Image">
      </figure>
      <figure class="ml-2 d-inline-block image is-50x50">
        <img src="http://openweathermap.org/img/w/{{ city.icon }}.png" alt="Image">
      </figure>
    </div>
  </div>
</div> -->




<div class="city_weather_page">
  <div class="container pt-3">
    <!-- {% for city in weather_data %} -->
    <h1>Current weather in {{ object.name }}</h1>
      <div class="row">
        <div class="col-sm-6">
          <figure class="ml-4 d-inline-block image is-50x50">
            <img src="http://openweathermap.org/img/w/{{ city.icon }}.png" alt="Image">
          </figure>
          <figure class="ml-5 d-inline-block image is-50x50">
            <img src="http://openweathermap.org/img/w/{{ city.icon }}.png" alt="Image">
          </figure>
          <figure class="ml-5 d-inline-block image is-50x50">
            <img src="http://openweathermap.org/img/w/{{ city.icon }}.png" alt="Image">
          </figure>
          <figure class="ml-5 d-inline-block image is-50x50">
            <img src="http://openweathermap.org/img/w/{{ city.icon }}.png" alt="Image">
          </figure>
          <figure class="ml-5 d-inline-block image is-50x50">
            <img src="http://openweathermap.org/img/w/{{ city.icon }}.png" alt="Image">
          </figure>
          <table id="city_detail_table" class="table table-bordered">
              <th>Description</th>
              <td>{{ city.description|capfirst }}</td>
            <tr>
              <th>Current Temp</th>
              <td>{{ city.temperature|floatformat:'0' }} ℉</td>
            </tr>
            <tr>
              <th>Today's low</th>
              <td>{{ city.temp_min|floatformat:'0' }} ℉</td>
            </tr>
            <tr>
              <th>Today's high</th>
              <td>{{ city.temp_max|floatformat:'0' }} ℉</td>
            </tr>
            <tr>
              <th>Relative Humidity</th>
              <td>{{ city.humidity }}%</td>
            </tr>
            <tr>
              <th>Wind Speed</th>
              <td>{{ city.wind_speed }} mph</td>
            </tr>
            <tr>
              <th>Barometric Pressure</th>
              <td>{{ city.pressure }} mb</td>
            </tr>
          </table>

          <!-- {% endfor %} -->

          <p><a class="btn btn-outline-info ml-2"  href="{% url 'weather:weather_list' %}">Back to Weather Main Page</a></p>
          <p><a class="btn btn-outline-info ml-2" href="{% url 'weather:city_delete' object.pk %}">Delete this city from saved list</a></p>
        </div>

      </div>
  </div>


</div>
{% endblock %}

templates/weather/new_city.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}Add city{% endblock %}
{% block styles %}
  <link rel="stylesheet" href="{% static '/discussion_board/css/styles.css' %}">
{% endblock %}

{% block content %}
<div class="weather_page">
  <div class="container pt-3">
    <h1 class="">Keep track of the weather in your favorite cities</h1>
    <form method="post">
      {% csrf_token %}
      {{ form|crispy }}
      <button class="btn btn-outline-info" type="submit">Add city</button>
    </form>
  </div>

</div>

{% endblock %}

templates/weather/weather.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}Weather{% endblock %}
{% block styles %}
  <link rel="stylesheet" href="{% static '/discussion_board/css/styles.css' %}">
{% endblock %}
{% block content %}
<div id="" class="weather_page">
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <h1 class="mt-3">Weather Page</h1>
          <h4 class="mb-3">Keep track of the weather in your favorite cities. Add the cities you want, delete the ones you don't.</h4>
          <p><a class="btn btn-outline-info" href="{% url 'weather:new_city' %}">Add a new city</a></p>
      </div>
    </div>

      <div class="row">
        {% for city in weather_data %}
        <div class="col-md-4">
          <div class="card mb-4 border-0">
            <div id="weather_card" class="card-body">
              <h4 class="card-text">{{ city.name }}</h4>

              <article class="media">
                <div class="media-left">
                  <figure class="image is-50x50">
                    <img src="http://openweathermap.org/img/w/{{ city.icon }}.png" alt="Image">
                  </figure>
                </div>
                <div class="media-content">
                  <div class="content">
                    <p>
                      <span class="title">{{ city.description|capfirst }}</span><br>
                      <span class="title">Current: {{  city.temperature|floatformat:'0' }} ℉</span><br>
                      <span class="title">Min: {{  city.temp_min|floatformat:'0' }} ℉</span><br>
                      <span class="title">Max: {{  city.temp_max|floatformat:'0' }} ℉</span><br>
                    </p>
                  </div>
                </div>
              </article>
              <div class="container text-center">
                <a class="btn btn-outline-info" href="{% url 'weather:city_detail' city.pk %}">Details</a>
                <a class="btn btn-outline-info" href="{% url 'weather:city_delete' city.pk %}">Delete</a>
              </div>


            </div>
          </div>
        </div>
        {% endfor %}
      </div>

  </div>

  </div>

{% endblock %}